name: llm_order_by
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - tqdm
  - pip:
      - openai
      - tiktoken
      - pydantic
      - httpx
      - diskcache
      - ir-datasets
      - pytrec-eval-terrier
      - adjustText
      - ddgs